project:
  type: website
  output-dir: _site
  preview:
    port: 5679
    browser: true
  render:
    - "!chunks/"
    - "!indicators-src/"
    - "**/*.qmd"
  resources:
    - images/
    - data/
    - data-raw/

website:
  title: climateindicators.us
  llms-txt: true
  site-url: https://climateindicators.us
  repo-url: https://github.com/climateindicators/climateindicators.us
  back-to-top-navigation: true
  open-graph:
    site-name: https://climateindicators.us
  page-footer:
    background: dark
    center:
      - text: "Site made with <i class='bi bi-heart-fill'></i>, <i class='bi bi-git'></i></a>, and <img src='/images/icon-quarto.svg' width=13 style='vertical-align:-1px;margin-right:0.25em'><a href='https://quarto.org/' target='_blank'>Quarto</a>"

  navbar:
    background: dark
    search: true
    left:
      - icon: house-door
        text: "climateindicators.us"
        href: index.qmd
      - icon: info-circle
        text: "About"
        href: about.qmd
      - icon: graph-up
        text: "Indicators"
        href: indicators.qmd

    right:
      - icon: github
        href: https://github.com/climateindicators/climateindicators.us

  sidebar:
    - title: "Indicators"
      style: "docked"
      background: light
      contents:
        - text: "All Indicators"
          href: indicators.qmd

        - section: "Health"
          contents:
            - text: "Heat-Related Deaths"
              href: indicators/heat-related-deaths.qmd
            - text: "Cold-Related Deaths"
              href: indicators/cold-related-deaths.qmd
            - text: "Heat-Related Workplace Deaths"
              href: indicators/heat-related-workplace-deaths.qmd
            - text: "Lyme Disease"
              href: indicators/lyme-disease.qmd
            

format:
  html:
    theme: [cosmo, css/theme.scss]
    code-fold: true
    code-summary: "Show code"
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    link-external-filter: '^(?:http:|https:)\/\/(?:www\.)?climateindicators\.us'

execute:
  echo: true
  eval: false
  warning: false
  message: false
code-link: true
knitr:
  opts_chunk:
    comment: "#>"
fig-retina: 3
toc-location: right
toc: true
