# Data access and figures for indicators/heat-related-deaths.qmd.
#
# HARD RULE (matches _common.R's scope for the site generally): this file
# reads data/heat-related-deaths/ and nothing else. It never opens
# data-raw/heat-related-deaths/ and never reaches the network.
#
# Canonical source: the sibling repo `heat-related-deaths`
# (github.com/climateindicators/heat-related-deaths). That repo holds the raw
# EPA inputs, the extraction pipeline (R/build_data.R), the docx narrative
# extraction (R/gen_narrative.R), and this same chart code
# (R/figures.R + relevant parts of _common.R). data/heat-related-deaths/ and
# data-raw/heat-related-deaths/ here are a copy of that repo's data/ and
# data-raw/ at the time of last sync — not generated by anything in this repo.
#
# TO RESYNC after that repo's data or charts change: re-copy
# heat-related-deaths/data/*.csv and meta.yml into data/heat-related-deaths/,
# and re-apply any figures.R changes here (the path-prefix diff is the only
# difference between that repo's R/figures.R and this file).

suppressPackageStartupMessages({
  library(ggplot2)
  library(ggiraph)
})

HRD_DATA_DIR <- here::here("data", "heat-related-deaths")

#' Read a generated heat-related-deaths dataset.
#'
#' Values are stored as text upstream so the source file's precision survives
#' byte for byte. This is where they become numeric, once, for plotting. Rows
#' carrying a suppression flag get NA, which is what makes the chart draw a
#' gap instead of a zero.
hrd_read <- function(file) {
  d <- readr::read_csv(
    file.path(HRD_DATA_DIR, file),
    col_types = readr::cols(.default = readr::col_character()),
    na = character(), progress = FALSE
  )
  d$value <- suppressWarnings(as.numeric(d$value))
  if ("year" %in% names(d)) d$year <- as.integer(d$year)
  if ("date" %in% names(d)) d$date <- as.Date(d$date)
  d
}

hrd_meta <- function() yaml::read_yaml(file.path(HRD_DATA_DIR, "meta.yml"))

hrd_meta_for <- function(file, meta = hrd_meta()) {
  hit <- Filter(function(d) identical(d$file, file), meta$datasets)
  if (length(hit) != 1L) stop("No meta.yml entry for ", file, call. = FALSE)
  hit[[1]]
}

# Chart styling. Font family is left as the theme default: SVG text metrics
# are resolved at build time, so pinning a family not installed everywhere
# makes the same chart render differently on a different machine.
hrd_theme <- function(base_size = 13) {
  theme_minimal(base_size = base_size) %+replace%
    theme(
      panel.grid.minor   = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.major.y = element_line(colour = "#dcdcd7", linewidth = 0.4),
      axis.title         = element_text(colour = "#464646", size = rel(0.9)),
      axis.text          = element_text(colour = "#464646"),
      axis.line.x        = element_line(colour = "#464646", linewidth = 0.4),
      plot.title         = element_blank(),
      plot.margin        = margin(4, 4, 4, 4),
      strip.text         = element_text(colour = "#1e1e1e", face = "bold",
                                        hjust = 0, size = rel(0.95)),
      legend.position    = "none"
    )
}

# Fixed three-slot categorical palette (blue/orange/aqua), validated for
# CVD-safe separation (dataviz skill's validate_palette.js), assigned by role
# rather than cycled: blue is always the baseline series, orange the one most
# worth the reader's attention, aqua a second comparison series. Never by
# position: Figure 2's caption names its colours in a different order than the
# source file lists its columns, so an index-based lookup would swap two
# series and still look plausible.
HRD_COLOURS <- c(
  underlying_all_year                = "#2a78d6",
  underlying_or_contributing_may_sep = "#eb6834",
  general                            = "#2a78d6",
  age_65_plus                        = "#eb6834",
  nh_black                           = "#1baf7a",
  deaths_avg_1990_2000               = "#2a78d6",
  deaths_1995                        = "#eb6834",
  high_temp_f                        = "#1baf7a"
)

hrd_label_colours <- function(d, key_col, label_col, order) {
  lab <- d[[label_col]][match(order, d[[key_col]])]
  setNames(unname(HRD_COLOURS[order]), lab)
}
hrd_label_order <- function(d, key_col, label_col, order) {
  d[[label_col]][match(order, d[[key_col]])]
}
hrd_legend_top <- function() {
  theme(
    legend.position   = "top",
    legend.title      = element_blank(),
    legend.justification = "left",
    legend.margin     = margin(0, 0, 6, 0),
    legend.text       = element_text(size = rel(0.85)),
    legend.key.width  = unit(1.4, "lines")
  )
}

HRD_GIRAFE_OPTS <- list(
  opts_hover(css = "stroke-width:3.5;"),
  opts_hover_inv(css = "opacity:0.3;"),
  opts_tooltip(css = paste(
    "background:#1e1e1e;color:#fff;padding:6px 10px;border-radius:4px;",
    "font-family:sans-serif;font-size:12px;"
  )),
  opts_toolbar(saveaspng = FALSE),
  opts_sizing(rescale = TRUE, width = 1)
)

hrd_girafe <- function(p, height = 4.2) {
  ggiraph::girafe(ggobj = p, width_svg = 8, height_svg = height, options = HRD_GIRAFE_OPTS)
}

# ---- Figure 1: annual heat-related death rates -------------------------------

hrd_fig_1_plot <- function() {
  d <- hrd_read("heat_deaths_annual.csv")
  # icd_revision splits the line at the classification change; series_key
  # alone would draw straight through 1998/1999.
  d$seg <- paste(d$series_key, d$icd_revision, sep = "/")
  order <- c("underlying_all_year", "underlying_or_contributing_may_sep")

  ggplot(d, aes(x = year, y = value, colour = series_label, group = seg)) +
    geom_line_interactive(linewidth = 0.9) +
    geom_point_interactive(
      aes(
        data_id = series_key,
        tooltip = sprintf(
          "%d — %s\n%.2f deaths per million (%s)",
          year, series_label, value, icd_revision
        )
      ),
      size = 2.2
    ) +
    scale_colour_manual(values = hrd_label_colours(d, "series_key", "series_label", order),
                       breaks = hrd_label_order(d, "series_key", "series_label", order)) +
    guides(colour = guide_legend(nrow = 2, byrow = TRUE)) +
    scale_x_continuous(breaks = seq(1980, 2020, 10)) +
    scale_y_continuous(limits = c(0, NA), expand = expansion(mult = c(0, 0.06))) +
    labs(x = NULL, y = "Death rate (per million people)") +
    hrd_theme() +
    hrd_legend_top()
}

hrd_fig_1 <- function() hrd_girafe(hrd_fig_1_plot())

hrd_fig_1_table <- function() {
  d <- hrd_read("heat_deaths_annual.csv")
  tidyr::pivot_wider(d, id_cols = year, names_from = series_label, values_from = value)
}

# ---- Figure 2: summer heat + cardiovascular disease death rates --------------

hrd_fig_2_plot <- function() {
  d <- hrd_read("heat_deaths_summer_cvd.csv")
  order <- c("general", "age_65_plus", "nh_black")
  d$population_key <- factor(d$population_key, levels = order)

  ggplot(d, aes(x = year, y = value, colour = population_label, group = population_key)) +
    geom_line_interactive(linewidth = 0.9) +
    geom_point_interactive(
      aes(
        data_id = population_key,
        tooltip = ifelse(
          flag == "suppressed",
          sprintf("%d — %s\nSuppressed: too few deaths to publish", year, population_label),
          sprintf("%d — %s\n%.2f deaths per million", year, population_label, value)
        )
      ),
      size = 2.2
    ) +
    scale_colour_manual(values = hrd_label_colours(d, "population_key", "population_label", order),
                       breaks = hrd_label_order(d, "population_key", "population_label", order)) +
    scale_x_continuous(breaks = seq(2000, 2020, 5)) +
    scale_y_continuous(limits = c(0, NA), expand = expansion(mult = c(0, 0.06))) +
    labs(x = NULL, y = "Death rate (per million people)") +
    hrd_theme() +
    hrd_legend_top()
}

hrd_fig_2 <- function() hrd_girafe(hrd_fig_2_plot())

hrd_fig_2_table <- function() {
  d <- hrd_read("heat_deaths_summer_cvd.csv")
  tidyr::pivot_wider(d, id_cols = year, names_from = population_label, values_from = value)
}

# ---- Example figure: 1995 Chicago heat wave -----------------------------------

HRD_EXAMPLE_PANEL_LABELS <- c(
  "deaths"             = "Number of daily deaths",
  "degrees Fahrenheit" = paste0("Daily high temperature (", intToUtf8(0x00B0), "F)")
)

hrd_fig_example_plot <- function() {
  d <- hrd_read("chicago_1995_heat_wave.csv")
  d$panel <- factor(HRD_EXAMPLE_PANEL_LABELS[d$unit], levels = unname(HRD_EXAMPLE_PANEL_LABELS))
  order <- c("deaths_avg_1990_2000", "deaths_1995", "high_temp_f")
  d$measure_key <- factor(d$measure_key, levels = order)

  # Shade the acute event: the contiguous run of days where 1995 deaths ran at
  # least 50 above the 1990-2000 average for that date. Derived from the data,
  # not copied from any published date range.
  wide <- tidyr::pivot_wider(d, id_cols = date, names_from = measure_key, values_from = value)
  excess_days <- wide$date[(wide$deaths_1995 - wide$deaths_avg_1990_2000) >= 50]
  highlight <- data.frame(xmin = min(excess_days), xmax = max(excess_days))

  # group is explicit because the tooltip string below is unique per row; left
  # implicit, ggplot infers grouping from every discrete aesthetic in a layer,
  # including tooltip, which would put each point in its own group of one and
  # silently break every line into isolated dots.
  ggplot(d, aes(x = date, y = value, colour = measure_label, group = measure_key)) +
    geom_rect(
      data = highlight, inherit.aes = FALSE,
      aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf),
      fill = "#2882e6", alpha = 0.08
    ) +
    geom_line_interactive(
      aes(
        data_id = measure_key, linetype = measure_key,
        tooltip = sprintf("%s\n%s: %.1f", format(date, "%B %d, %Y"), measure_label, value)
      ),
      linewidth = 0.8
    ) +
    facet_wrap(~panel, ncol = 1, scales = "free_y") +
    scale_colour_manual(
      values = hrd_label_colours(d, "measure_key", "measure_label", order),
      breaks = hrd_label_order(d, "measure_key", "measure_label", order[1:2])
    ) +
    scale_linetype_manual(
      values = setNames(c("solid", "solid", "22"), order),
      guide = "none"
    ) +
    scale_x_date(date_labels = "%b %d", date_breaks = "2 weeks") +
    labs(x = NULL, y = NULL) +
    hrd_theme() +
    hrd_legend_top() +
    theme(panel.spacing = unit(1, "lines"))
}

hrd_fig_example <- function() hrd_girafe(hrd_fig_example_plot(), height = 5.2)

hrd_fig_example_table <- function() {
  d <- hrd_read("chicago_1995_heat_wave.csv")
  tidyr::pivot_wider(d, id_cols = date, names_from = measure_label, values_from = value)
}
